let words = [
    "crisis",
    "unanimous",
    "javascript",
    "flutter",
    "financial",
    "license",
    "loot",
    "salesperson",
    "class",
    "function",
    "python",
    "cane",
    "key",
    "deserve",
    "exempt",
    "glide",
    "forget",
    "wire",
    "consideration",
    "absorption",
    "sharp",
    "goalkeeper",
    "grand",
    "react",
    "redux",
    "express",
    "node",
    "vue",
    "hue",
    "coin",
    "revival",
    "private",
    "hit",
    "bland",
    "adamant",
    "curl",
    "superintendent",
    "rehabilitation",
    "characteristic",
    "jam",
    "obese",
    "confession",
    "battery",
    "salon",
    "factor",
    "delay",
    "cemetery",
    "rank",
    "admonish",
    "generation",
    "misspell",
    "pronunciation",
    "conceive",
    "goat",
    "quarrel",
    "workshop",
    "dough",
    "myth",
    "cooperation",
    "exhibition",
    "orange",
    "angular",
    "html",
    "css",
    "lambda",
    "destructor",
    "object",
    "possession",
    "abstruse",
    "accost",
    "anachronistic",
    "antiseptic",
    "antithesis",
    "nature",
    "radiation",
    "circumvent",
    "commensurate",
    "contentious",
    "demagogue",
    "disaffected",
    "egregious",
    "embezzlement",
    "heterogenous",
];

let deletedWords = [];

//Return a new random word from the array
const getNewWord = (hasStarted) => {
    const randomIndex = Math.floor(Math.random() * words.length);
    const newWord = words[randomIndex];
    if (hasStarted) {
        deletedWords.push(...words.splice(randomIndex, 1));
    } else {
        words = [...words, ...deletedWords];
        deletedWords = [];
    }
    return newWord;
};
